language: java
jdk:
  - oraclejdk8
dist: trusty

addons:
  sonarcloud:
    organization: "yallisonmelo"
    #token:
     # secure: "**************************" # encrypted value of your token

script:
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=yallisonmelo_TheIntegrations
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
